# Generated by Django 4.0.2 on 2022-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="test_testererer",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
