# Generated by Django 4.0.2 on 2022-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_testerer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artists",
            name="first_name",
            field=models.CharField(max_length=200),
        ),
    ]
