# Generated by Django 4.0.2 on 2022-02-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_artists_first_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artists",
            new_name="Artist",
        ),
        migrations.DeleteModel(
            name="Testerer",
        ),
    ]
