# Generated by Django 4.0.2 on 2022-02-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_sponsor_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SponsorImage",
        ),
    ]
