# Generated by Django 4.0.2 on 2022-02-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_sponsorimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("image", models.FileField(upload_to="images/")),
                ("currentHead", models.BooleanField()),
            ],
        ),
    ]
