# Generated by Django 4.0.2 on 2022-02-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_frontheading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frontheading",
            name="list_order",
        ),
    ]
