# Generated by Django 4.0.2 on 2022-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_frontheading_list_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavbarHeadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=200)),
                ("artists", models.CharField(max_length=200)),
                ("attractions", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
            ],
        ),
    ]
